# Generated by Django 3.1.3 on 2021-09-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sso', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sso', models.BooleanField(default=False)),
            ],
        ),
    ]
