# Generated by Django 3.0.6 on 2020-06-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(max_length=6)),
                ('program_title', models.CharField(max_length=100)),
                ('faculty_code', models.CharField(max_length=5)),
                ('educ_level', models.CharField(max_length=5)),
            ],
        ),
    ]
