# Generated by Django 3.1.2 on 2020-11-12 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentauth',
            unique_together={('sheridan_id', 'password')},
        ),
    ]
