# Generated by Django 3.1.2 on 2020-11-21 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentauth', '0002_auto_20201113_0741'),
        ('studentauth', '0002_auto_20201111_2116'),
    ]

    operations = [
    ]
