# Generated by Django 3.0.4 on 2020-09-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_year', models.IntegerField(default=1)),
                ('num_of_students', models.IntegerField(default=1)),
                ('program_type', models.CharField(max_length=70)),
                ('grades', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
