# Generated by Django 3.1.3 on 2021-09-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('program_year', models.IntegerField(default=1)),
                ('program_type', models.CharField(max_length=70)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('co_op', models.BooleanField()),
                ('international', models.BooleanField()),
            ],
        ),
    ]
