# Generated by Django 3.0.4 on 2020-10-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='grades',
            new_name='grade',
        ),
        migrations.RemoveField(
            model_name='school',
            name='num_of_students',
        ),
        migrations.AddField(
            model_name='school',
            name='co_op',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='international',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
