# Generated by Django 3.1.3 on 2021-09-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentConsultantForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1e_sso', models.BooleanField(default=False)),
                ('q1e_friend', models.BooleanField(default=False)),
                ('q1e_faculty', models.BooleanField(default=False)),
                ('q1e_visit', models.BooleanField(default=False)),
                ('q1e_orient', models.BooleanField(default=False)),
                ('q1e_event', models.BooleanField(default=False)),
                ('q1e_kpi2', models.BooleanField(default=False)),
                ('q1e_outreach', models.BooleanField(default=False)),
                ('q1e_posters', models.BooleanField(default=False)),
                ('q1e_stv', models.BooleanField(default=False)),
                ('q1e_social', models.BooleanField(default=False)),
                ('q1e_media', models.BooleanField(default=False)),
                ('q1e_walkby', models.BooleanField(default=False)),
                ('q1e_website', models.BooleanField(default=False)),
                ('ecs_resume', models.BooleanField(default=True)),
                ('ecs_cover', models.BooleanField(default=True)),
                ('ecs_interview', models.BooleanField(default=True)),
                ('ecs_jobsearch', models.BooleanField(default=True)),
                ('ecs_mockinterview', models.BooleanField(default=True)),
                ('ecs_networking', models.BooleanField(default=True)),
                ('ecs_portfolio', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('q1e_sso', 'q1e_friend', 'q1e_faculty', 'q1e_visit', 'q1e_orient', 'q1e_event', 'q1e_kpi2', 'q1e_outreach', 'q1e_posters', 'q1e_stv', 'q1e_social', 'q1e_media', 'q1e_walkby', 'q1e_website', 'ecs_resume', 'ecs_cover', 'ecs_interview', 'ecs_jobsearch', 'ecs_mockinterview', 'ecs_networking', 'ecs_portfolio')},
            },
        ),
    ]
