# Generated by Django 3.1.2 on 2020-10-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentConsultantForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1e_sso', models.BooleanField(default=False)),
                ('q1e_friend', models.BooleanField(default=False)),
                ('q1e_faculty', models.BooleanField(default=False)),
                ('q1e_visit', models.BooleanField(default=False)),
                ('q1e_orient', models.BooleanField(default=False)),
                ('q1e_event', models.BooleanField(default=False)),
                ('q1e_kpi2', models.BooleanField(default=False)),
                ('q1e_outreach', models.BooleanField(default=False)),
                ('q1e_posters', models.BooleanField(default=False)),
                ('q1e_stv', models.BooleanField(default=False)),
                ('q1e_social', models.BooleanField(default=False)),
                ('q1e_media', models.BooleanField(default=False)),
                ('q1e_walkby', models.BooleanField(default=False)),
                ('q1e_website', models.BooleanField(default=False)),
                ('ecs_exploration', models.BooleanField(default=False)),
                ('ecs_eplanning', models.BooleanField(default=False)),
                ('ecs_cplanning', models.BooleanField(default=False)),
                ('ecs_labourmarket', models.BooleanField(default=False)),
                ('ecs_other', models.BooleanField(default=False)),
            ],
        ),
    ]
