# Generated by Django 3.1.2 on 2020-10-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employmentform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentconsultantform',
            name='ecs_cplanning',
        ),
        migrations.RemoveField(
            model_name='employmentconsultantform',
            name='ecs_eplanning',
        ),
        migrations.RemoveField(
            model_name='employmentconsultantform',
            name='ecs_exploration',
        ),
        migrations.RemoveField(
            model_name='employmentconsultantform',
            name='ecs_labourmarket',
        ),
        migrations.RemoveField(
            model_name='employmentconsultantform',
            name='ecs_other',
        ),
        migrations.AddField(
            model_name='employmentconsultantform',
            name='ecs_cover',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employmentconsultantform',
            name='ecs_interview',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employmentconsultantform',
            name='ecs_jobsearch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employmentconsultantform',
            name='ecs_mockinterview',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employmentconsultantform',
            name='ecs_networking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employmentconsultantform',
            name='ecs_portfolio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employmentconsultantform',
            name='ecs_resume',
            field=models.BooleanField(default=True),
        ),
    ]
