# Generated by Django 3.1.3 on 2021-09-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('employmentform', '0001_initial'),
        ('careerform', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('submission_date', models.DateTimeField(null=True)),
                ('approval_date', models.DateTimeField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('student_notes', models.CharField(max_length=300, null=True)),
                ('staff_notes', models.CharField(max_length=300, null=True)),
                ('attachment1', models.CharField(max_length=300, null=True)),
                ('attachment2', models.CharField(max_length=300, null=True)),
                ('attachment3', models.CharField(max_length=300, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('delete_appointment_row', models.BooleanField(blank=True, default=False, null=True)),
                ('cc_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='careerform.careercounselorform')),
                ('ec_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employmentform.employmentconsultantform')),
                ('staff_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffaccount')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentaccount')),
            ],
        ),
    ]
