# Generated by Django 3.0.4 on 2020-04-04 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('submission_date', models.DateTimeField()),
                ('approval_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('student_notes', models.CharField(max_length=300)),
                ('staff_notes', models.CharField(max_length=300)),
                ('attachment1', models.CharField(max_length=300)),
                ('attachment2', models.CharField(max_length=300)),
                ('attachment3', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=20)),
                ('delete_appointment_row', models.BooleanField(default=False)),
                ('cc_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='careerform.careercounselorform')),
                ('ec_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employmentform.employmentconsultantform')),
                ('staff_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffaccount')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentaccount')),
            ],
        ),
    ]
