# Generated by Django 3.0.4 on 2020-04-06 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='student',
        ),
    ]
