# Generated by Django 3.1.2 on 2020-11-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='approval_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='attachment1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='attachment2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='attachment3',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff_notes',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='student_notes',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='submission_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
