# Generated by Django 3.1.3 on 2020-11-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employmentform', '0002_auto_20201023_1909'),
        ('staff', '0002_remove_staffaccount_tel'),
        ('student', '0008_auto_20201030_1626'),
        ('careerform', '0002_auto_20201023_1908'),
        ('appointments', '0001_initial'),
    ]
    # seems like you can't put a 3 ''' comment inbetween these migrations or youl get an error
    operations = [
        migrations.AddField(
            model_name='appointment',
            name='delete_appointment_row',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='attachment2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='attachment3',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
