# Generated by Django 3.1.3 on 2020-11-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20201113_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='delete_appointment_row',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
