# Generated by Django 3.1.3 on 2020-11-13 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employmentform', '0002_auto_20201023_1909'),
        ('staff', '0002_remove_staffaccount_tel'),
        ('careerform', '0002_auto_20201023_1908'),
        ('student', '0008_auto_20201030_1626'),
        ('appointments', '0002_auto_20201113_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attachment1',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
