# Generated by Django 3.1.3 on 2020-11-13 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20201030_1626'),
        ('employmentform', '0002_auto_20201023_1909'),
        ('careerform', '0002_auto_20201023_1908'),
        ('staff', '0002_remove_staffaccount_tel'),
        ('appointments', '0003_auto_20201113_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='approval_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cc_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='careerform.careercounselorform'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ec_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employmentform.employmentconsultantform'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffaccount'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff_notes',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentaccount'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='student_notes',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='submission_date',
            field=models.DateTimeField(null=True),
        ),
    ]
