# Generated by Django 3.1.2 on 2020-11-30 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20201113_1540'),
        ('appointments', '0003_auto_20201116_1154'),
    ]

    operations = [
    ]
