# Generated by Django 3.1.2 on 2020-12-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_merge_20201129_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
