# Generated by Django 3.1.2 on 2020-11-21 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20201113_0624'),
        ('appointments', '0002_auto_20201113_1540'),
    ]

    operations = [
    ]
