# Generated by Django 3.1.2 on 2020-10-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20201014_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='approval_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='submission_date',
            field=models.DateTimeField(null=True),
        ),
    ]
