# Generated by Django 3.1.2 on 2020-11-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_merge_20201121_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='delete_appointment_row',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
