# Generated by Django 3.1.3 on 2021-09-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentauth', '0001_initial'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(max_length=50, null=True)),
                ('gpa', models.CharField(max_length=5, null=True)),
                ('program_year', models.CharField(max_length=2, null=True)),
                ('als', models.BooleanField(null=True)),
                ('coop', models.BooleanField(null=True)),
                ('international', models.BooleanField(null=True)),
                ('fname', models.CharField(max_length=50, null=True)),
                ('lname', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('student_number', models.CharField(max_length=15, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('student_status', models.CharField(max_length=4, null=True)),
                ('auth_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentauth.studentauth')),
                ('program_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.schoolprogram')),
            ],
        ),
    ]
