# Generated by Django 3.0.6 on 2020-06-02 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, null=True)),
                ('lname', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('student_number', models.CharField(max_length=15, null=True)),
                ('program_year', models.IntegerField(default=1)),
                ('als', models.BooleanField(default=False)),
                ('coop', models.BooleanField(default=False)),
                ('international', models.BooleanField(default=False)),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.SchoolProgram')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheridan_id', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentAccount')),
            ],
        ),
    ]
