# Generated by Django 3.1.2 on 2020-10-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20201008_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='phone_number',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='program_year',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
