# Generated by Django 3.1.2 on 2020-10-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20201008_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
