# Generated by Django 3.1.2 on 2020-11-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20201030_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='program_year',
            field=models.IntegerField(null=True),
        ),
    ]
