# Generated by Django 3.1.2 on 2020-11-12 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
        ('studentauth', '0002_auto_20201111_2116'),
        ('student', '0009_auto_20201111_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='als',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='auth_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentauth.studentauth'),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='coop',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='international',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='program_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.schoolprogram'),
        ),
    ]
