# Generated by Django 3.1.2 on 2020-11-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20201111_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='program_year',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
