# Generated by Django 3.1.2 on 2020-11-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20201111_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='student_status',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentaccount',
            unique_together=set(),
        ),
    ]
