# Generated by Django 3.0.4 on 2020-11-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_studentaccount_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='education_level',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='grade',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
