# Generated by Django 3.0.4 on 2020-11-26 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20201126_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentaccount',
            old_name='grade',
            new_name='gpa',
        ),
    ]
