# Generated by Django 3.1.2 on 2020-12-03 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20201126_1803'),
        ('student', '0012_auto_20201129_1953'),
    ]

    operations = [
    ]
